# Generated by Django 3.1.3 on 2020-11-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='タイトル')),
                ('types', models.IntegerField(choices=[(1, 'メインストーリー'), (2, '外伝'), (3, 'オリジナルタスク'), (4, 'その他')], verbose_name='タイプ')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='詳細')),
                ('condition', models.IntegerField(choices=[(1, '新規'), (2, '挑戦中'), (3, '完了')], default=1, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('main_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.maintask')),
            ],
        ),
    ]
